language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coverage codecov
  - pip install .

# command to run tests
script:
  - python -c "import rex"
  - coverage run -m unittest -v && coverage report

after_success:
  - bash <(curl -s https://codecov.io/bash)
