name: Question
description: Ask a question
title: "[Question]: "
labels: ["question"]
assignees:
  - Spico197
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Please tell us, what can I help you?
      placeholder: Content goes here
      value: "My question is ..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Spico197/REx/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
