# task
task_name: ERE_CasRel_WebNLG

# data preprocessing
max_seq_len: 300

# filepaths
data_dir: /data4/tzhu/REx/data/WebNLG/formatted
bert_model_dir: /data4/tzhu/pretrained_model/bert-base-uncased
train_filepath: ${data_dir}/train.linejson
dev_filepath: ${data_dir}/dev.linejson
test_filepath: ${data_dir}/valid.linejson
rel2id_filepath: ${data_dir}/rel2id.json
output_dir: /data4/tzhu/REx/examples/JointERE/outputs
task_dir: ${output_dir}/${task_name}
load_train_data: True
load_dev_data: True
load_test_data: True

# training
skip_train: false
device: 3
local_rank: -1
random_seed: 1227
num_epochs: 10
num_early_stop: -1
train_batch_size: 16
eval_batch_size: 1  # for CasRel, the evaluating batch size must be 1
learning_rate: 3e-5
save_best_ckpt: true
debug_mode: false  # if debug mode, a small subset of the whole dataset will be activated

# eval
pred_threshold: 0.5

# logging
only_master_logging: true
