# task
task_name: dummy_task
comment: 'demo task'

# data preprocessing
max_seq_len: 512

# filepaths
data_dir: /path/to/data
plm_dir: /path/to/plm/folder
train_filepath: ${data_dir}/train.json
dev_filepath: ${data_dir}/dev.json
test_filepath: ${data_dir}/test.json
output_dir: outputs/
task_dir: ${output_dir}/${task_name}

# training
skip_train: false
skip_final_eval: false
final_eval_model_filepath: ${task_dir}/ckpt/${model_type}.best.pth
skip_predict_example: false
debug_mode: false

device: 3
random_seed: 1227
num_epochs: 10
num_early_stop: 3
train_batch_size: 8
eval_batch_size: 8
learning_rate: !!float 1e-5
save_best_ckpt: true

# logging
only_master_logging: true

# model
dropout: 0.5
num_filters: 300
