# task
task_type: MCMLSentRelationClassificationTask
task_name: re_sent_IPRE

# data preprocessing
max_seq_len: 100
dim_token_emb: 300

# filepaths
train_filepath: data/IPRE/formatted/train.linejson
dev_filepath: data/IPRE/formatted/dev.linejson
test_filepath: data/IPRE/formatted/test.linejson
emb_filepath: data/IPRE/vocab.emb
rel2id_filepath: data/IPRE/label2id.json
data_cache_dir: data/IPRE/cache
output_dir: examples/IPRE/outputs
task_dir: ${output_dir}/${task_name}

# training
skip_train: false
resumed_training: false
grad_accum_steps: 1
max_grad_norm: -1
step_eval_interval: -1
epoch_eval_interval: 1
select_best_by_key: metric
eval_on_data: [dev]
select_best_on_data: dev
best_metric_field: micro.f1
local_rank: -1
random_seed: 1227
num_epochs: 1
num_early_stop: 5
train_batch_size: 64
eval_batch_size: 64
learning_rate: 1e-3
save_best_ckpt: true
debug_mode: false  # if debug mode, a small subset of the whole dataset will be activated

# eval
pred_threshold: 0.5

# model
num_filters: 230
kernel_size: 5
dim_pos_emb: 10
dropout: 0.5
