# task
task_name: re_sent_IPRE

# data preprocessing
max_seq_len: 100
dim_token_emb: 300

# filepaths
train_filepath: /data4/tzhu/REx/data/IPRE/formatted/train.linejson
dev_filepath: /data4/tzhu/REx/data/IPRE/formatted/dev.linejson
test_filepath: /data4/tzhu/REx/data/IPRE/formatted/test.linejson
emb_filepath: /data4/tzhu/CCKS2020-FinEBody-nonNaN/data/sgns.sogounews.bigram-char
output_dir: /data4/tzhu/REx/examples/IPRE/outputs
task_dir: ${output_dir}/${task_name}

# training
skip_train: false
device: 0
local_rank: -1
random_seed: 1227
num_epochs: 1
num_early_stop: 5
train_batch_size: 64
eval_batch_size: 64
learning_rate: 1e-3
save_best_ckpt: true
debug_mode: false  # if debug mode, a small subset of the whole dataset will be activated

# eval
pred_threshold: 0.5

# logging
only_master_logging: true

# model
num_filters: 230
kernel_size: 5
dim_pos_emb: 10
dropout: 0.5
